    [build]
      command = "npm run build"
      publish = "build" # For Create React App; if you used Vite, change this to "dist"

    [functions]
      directory = "netlify/functions"
      node_bundler = "esbuild" # Recommended for faster builds