 [build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # Mark specific firebase-admin sub-modules as external for esbuild
  external_node_modules = [
    "firebase-admin/app",
    "firebase-admin/firestore"
  ]
